---
Sections:
  VERSION 9:
    order: 1
    entries:
    - name : Version Begins
      file : VersionBegin.md
      order : 10

  Brighter Configuration:
    order: 20
    entries:
    - name : Basic Configuration
      file : BrighterBasicConfiguration.md
      order : 10
    - name : RabbitMQ Configuration
      file : RabbitMQConfiguration.md
      order : 40
    - name : AWS SNS Configuration
      file : AWSSQSConfiguration.md
      order : 50
    - name : Kafka Configuration
      file : KafkaConfiguration.md
      order : 60
    - name : Azure Service Bus Configuration
      file: AzureServiceBusConfiguration.md
      order : 70

  Guaranteed At Least Once:
    order: 50
    entries:
    - name: EFCore Outbox 
      file: EFCoreOutbox.md
      order : 30
    - name : Dapper Outbox 
      file : DapperOutbox.md
      order : 40
    - name : Dynamo Outbox 
      file : DynamoOutbox.md
      order : 50
    - name : MSSQL Inbox
      file : MSSQLInbox.md
      order : 60
    - name : MySQL Inbox
      file : MySQLInbox.md
      order : 70
    - name : Postgres Inbox
      file : PostgresInbox.md
      order : 80
    - name : Sqlite Inbox
      file : SqliteInbox.md
      order : 90
    - name : Dynamo Inbox
      file : DynamoInbox.md
      order : 100

  END OF VERSION:
    order: 999
    entries:   
    - name : Version Ends
      file : VersionEnd.md
      order : 20
...
