---
Sections:
  VERSION 10:
    order: 1
    entries:
    - name : Version Begins
      file : VersionBegin.md
      order : 10
  Overview:
    order: 10
    entries:
    - name : Show me the code!
      file : ShowMeTheCode.md
      order : 10
      
  Brighter Configuration:
    order: 20
    entries:
    - name : Basic Configuration
      file : BrighterBasicConfiguration.md
      order : 10
    - name : RabbitMQ Configuration
      file : RabbitMQConfiguration.md
      order : 40
    - name : AWS SNS Configuration
      file : AWSSQSConfiguration.md
      order : 50
    - name : Kafka Configuration
      file : KafkaConfiguration.md
      order : 60
    - name : Azure Service Bus Configuration
      file: AzureServiceBusConfiguration.md
      order : 70
  
  Guaranteed At Least Once:
    order: 50
    entries:
    - name: MSSQL Outbox 
      file: MSSQLOutbox.md
      order : 30
    - name: MySQL Outbox 
      file: MySQLOutbox.md
      order : 40
    - name: Postgres Outbox 
      file: PostgresOutbox.md
      order : 50
    - name: Postgres Outbox 
      file: PostgresOutbox.md
      order : 60
    - name: Sqlite Outbox 
      file: SqliteOutbox.md
      order : 70
    - name : Dapper Outbox 
      file : DapperOutbox.md
      order : 80
    - name : Dynamo Outbox 
      file : DynamoOutbox.md
      order : 90
    - name : MongoDb Outbox 
      file : MongoDBOutbox.md
      order : 100
    - name : MSSQL Inbox
      file : MSSQLInbox.md
      order : 110
    - name : MySQL Inbox
      file : MySQLInbox.md
      order : 120
    - name : Postgres Inbox
      file : PostgresInbox.md
      order : 130
    - name : Sqlite Inbox
      file : SqliteInbox.md
      order : 140
    - name : Dynamo Inbox
      file : DynamoInbox.md
      order : 150
    - name : MongoDb Inbox
      file : MongoDbInbox.md
      order : 160

  END OF VERSION:
    order: 999
    entries:   
    - name : Version Ends
      file : VersionEnd.md
      order : 20
...